const CACHE_NAME = 'profilscan-v1.5.10';
const ASSETS = [
  './',
  './index.html',
  './visual-compare.html',
  './pipeline-debug.html',
  './pipeline-compare.html',
  './manifest.json',
  './configs/validated-default.json',
  './src/app/ui.css',
  './src/app/app.js',
  './src/app/app-main.js',
  './src/app/auto-settings.js',
  './src/app/batch-benchmark.js',
  './src/app/benchmark-weight-presets.js',
  './src/app/camera.js',
  './src/app/config-manager.js',
  './src/app/image-import.js',
  './src/app/live-slider-preview.js',
  './src/app/observability-dashboard.js',
 